---
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

bootstrap_hostname: vm-rui
bootstrap_admin_user: cosmin
bootstrap_admin_groups:
  - sudo
bootstrap_admin_shell: /bin/bash
bootstrap_admin_ssh_keys: []
bootstrap_enable_passwordless_sudo: true

common_upgrade_packages: true
common_reboot_after_upgrade: false
common_timezone: Europe/Bucharest
common_enable_qemu_guest_agent: true
common_enable_ufw: false
common_ufw_allowed_tcp_ports:
  - 22
common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - fail2ban
  - git
  - htop
  - jq
  - net-tools
  - sudo
  - unzip
  - vim

docker_users:
  - "{{ bootstrap_admin_user }}"
