---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reload auditd
  ansible.builtin.command:
    cmd: augenrules --load
  changed_when: true
