---
common_packages: []
common_upgrade_packages: true
common_reboot_after_upgrade: false
common_timezone: UTC
common_enable_qemu_guest_agent: false
common_enable_ufw: false
common_ufw_allowed_tcp_ports:
  - 22
